import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      exclude: [
        "src/index.ts",
        // Type re-exports + one pre-proto interface; no runtime code.
        "src/relay/protocol.ts",
        // Generated by protoc-gen-es; covered by shape tests elsewhere.
        "src/relay/pb/**",
      ],
      thresholds: {
        lines: 90,
        functions: 90,
      },
    },
  },
});
