import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      exclude: [
        // CLI bin: thin argv parser + signal wiring around startServer.
        // Covered by tests/index.test.ts subprocess smoke (--check), not by
        // unit coverage — the file's only runtime path is process.exit().
        "src/index.ts",
        // Integration wiring (express app + RelayServer + Grant + broker
        // routes). The dryRun and real-listen tests in tests/start.test.ts
        // exercise the load/wire/listen happy path; the per-route handlers
        // are themselves tested directly via the broker/router/status/relay
        // suites. Pulling every plumbing branch into coverage would just
        // duplicate those existing tests against an express app.
        "src/start.ts",
        // Type re-exports + one pre-proto interface; no runtime code.
        "src/relay/protocol.ts",
        // Generated by protoc-gen-es; covered by shape tests elsewhere.
        "src/relay/pb/**",
      ],
      thresholds: {
        lines: 90,
        functions: 90,
      },
    },
  },
});
