// Protocol schema for the dicode relay WebSocket tunnel.
//
// Single source of truth, generated on both sides:
//   - dicode-core (Go)    via protoc-gen-go → pkg/relay/pb/*.pb.go
//   - dicode-relay (Node) via protoc-gen-es → src/relay/pb/*.ts
//
// Wire format is JSON (WebSocket text frames). protojson (Go) and
// @bufbuild/protobuf's fromJson/toJson (Node) produce matching output.
//
// Protocol version: 3 (first generated-from-proto release). Bumping from v2
// is mandatory because two on-wire shapes changed:
//   - headers: previously a JSON object with string-array values, now nested
//     through HeaderValues. Proto3 maps cannot hold repeated values directly.
//   - timestamp: kept as int32 to keep protojson emitting it as a JSON number
//     instead of a quoted string (its default encoding for int64).
//
// Both sides MUST reject connections where the peer advertises protocol < 3.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file relay.proto (package dicode.relay.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file relay.proto.
 */
export const file_relay: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CgtyZWxheS5wcm90bxIPZGljb2RlLnJlbGF5LnYxIssBCg1TZXJ2ZXJNZXNzYWdlEi8KCWNoYWxsZW5nZRgBIAEoCzIaLmRpY29kZS5yZWxheS52MS5DaGFsbGVuZ2VIABIrCgd3ZWxjb21lGAIgASgLMhguZGljb2RlLnJlbGF5LnYxLldlbGNvbWVIABInCgVlcnJvchgDIAEoCzIWLmRpY29kZS5yZWxheS52MS5FcnJvckgAEisKB3JlcXVlc3QYBCABKAsyGC5kaWNvZGUucmVsYXkudjEuUmVxdWVzdEgAQgYKBGtpbmQibwoNQ2xpZW50TWVzc2FnZRInCgVoZWxsbxgBIAEoCzIWLmRpY29kZS5yZWxheS52MS5IZWxsb0gAEi0KCHJlc3BvbnNlGAIgASgLMhkuZGljb2RlLnJlbGF5LnYxLlJlc3BvbnNlSABCBgoEa2luZCIaCglDaGFsbGVuZ2USDQoFbm9uY2UYASABKAkiXQoFSGVsbG8SDAoEdXVpZBgBIAEoCRIOCgZwdWJrZXkYAiABKAkSFgoOZGVjcnlwdF9wdWJrZXkYAyABKAkSCwoDc2lnGAQgASgJEhEKCXRpbWVzdGFtcBgFIAEoBSJoCgdXZWxjb21lEgsKA3VybBgBIAEoCRIaCg1icm9rZXJfcHVia2V5GAIgASgJSACIAQESFQoIcHJvdG9jb2wYAyABKAVIAYgBAUIQCg5fYnJva2VyX3B1YmtleUILCglfcHJvdG9jb2wiGAoFRXJyb3ISDwoHbWVzc2FnZRgBIAEoCSLIAQoHUmVxdWVzdBIKCgJpZBgBIAEoCRIOCgZtZXRob2QYAiABKAkSDAoEcGF0aBgDIAEoCRI2CgdoZWFkZXJzGAQgAygLMiUuZGljb2RlLnJlbGF5LnYxLlJlcXVlc3QuSGVhZGVyc0VudHJ5EgwKBGJvZHkYBSABKAkaTQoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEoCRIsCgV2YWx1ZRgCIAEoCzIdLmRpY29kZS5yZWxheS52MS5IZWFkZXJWYWx1ZXM6AjgBIrwBCghSZXNwb25zZRIKCgJpZBgBIAEoCRIOCgZzdGF0dXMYAiABKAUSNwoHaGVhZGVycxgDIAMoCzImLmRpY29kZS5yZWxheS52MS5SZXNwb25zZS5IZWFkZXJzRW50cnkSDAoEYm9keRgEIAEoCRpNCgxIZWFkZXJzRW50cnkSCwoDa2V5GAEgASgJEiwKBXZhbHVlGAIgASgLMh0uZGljb2RlLnJlbGF5LnYxLkhlYWRlclZhbHVlczoCOAEiHgoMSGVhZGVyVmFsdWVzEg4KBnZhbHVlcxgBIAMoCSKNAQoST0F1dGhUb2tlbkRlbGl2ZXJ5EhIKCnNlc3Npb25faWQYASABKAkSGAoQZXBoZW1lcmFsX3B1YmtleRgCIAEoCRISCgpjaXBoZXJ0ZXh0GAMgASgJEg0KBW5vbmNlGAQgASgJEhcKCmJyb2tlcl9zaWcYBSABKAlIAIgBAUINCgtfYnJva2VyX3NpZ0IvWi1naXRodWIuY29tL2RpY29kZS9kaWNvZGUvcGtnL3JlbGF5L3BiO3JlbGF5cGJiBnByb3RvMw",
  );

/**
 * ServerMessage is any message the relay server sends to the daemon.
 * Wire form: a JSON object with one key identifying the variant, e.g.
 *   {"challenge": {"nonce": "..."}}.
 *
 * @generated from message dicode.relay.v1.ServerMessage
 */
export type ServerMessage = Message<"dicode.relay.v1.ServerMessage"> & {
  /**
   * @generated from oneof dicode.relay.v1.ServerMessage.kind
   */
  kind:
    | {
        /**
         * @generated from field: dicode.relay.v1.Challenge challenge = 1;
         */
        value: Challenge;
        case: "challenge";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Welcome welcome = 2;
         */
        value: Welcome;
        case: "welcome";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Error error = 3;
         */
        value: Error;
        case: "error";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Request request = 4;
         */
        value: Request;
        case: "request";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message dicode.relay.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> =
  /*@__PURE__*/
  messageDesc(file_relay, 0);

/**
 * ClientMessage is any message the daemon sends to the relay server.
 *
 * @generated from message dicode.relay.v1.ClientMessage
 */
export type ClientMessage = Message<"dicode.relay.v1.ClientMessage"> & {
  /**
   * @generated from oneof dicode.relay.v1.ClientMessage.kind
   */
  kind:
    | {
        /**
         * @generated from field: dicode.relay.v1.Hello hello = 1;
         */
        value: Hello;
        case: "hello";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Response response = 2;
         */
        value: Response;
        case: "response";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message dicode.relay.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> =
  /*@__PURE__*/
  messageDesc(file_relay, 1);

/**
 * Challenge is the first frame the server sends: a 32-byte random nonce
 * hex-encoded (64 lowercase hex chars).
 *
 * @generated from message dicode.relay.v1.Challenge
 */
export type Challenge = Message<"dicode.relay.v1.Challenge"> & {
  /**
   * @generated from field: string nonce = 1;
   */
  nonce: string;
};

/**
 * Describes the message dicode.relay.v1.Challenge.
 * Use `create(ChallengeSchema)` to create a new message.
 */
export const ChallengeSchema: GenMessage<Challenge> = /*@__PURE__*/ messageDesc(file_relay, 2);

/**
 * Hello is the daemon's handshake reply. The daemon signs
 * sha256(nonce_bytes || timestamp_be_uint64) with its ECDSA P-256 signing key.
 *
 * @generated from message dicode.relay.v1.Hello
 */
export type Hello = Message<"dicode.relay.v1.Hello"> & {
  /**
   * hex(sha256(uncompressed_pubkey)) — 64 lowercase hex chars.
   *
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * Base64 std-encoded 65-byte uncompressed P-256 public key (0x04 || X || Y).
   * Used for ECDSA verification (WSS handshake + /auth/:provider sigs).
   *
   * @generated from field: string pubkey = 2;
   */
  pubkey: string;

  /**
   * Base64 std-encoded 65-byte uncompressed P-256 public key (0x04 || X || Y).
   * Used as the ECIES recipient on OAuth token delivery (dicode-core#104).
   * Required — every daemon now ships with a split sign/decrypt identity.
   *
   * @generated from field: string decrypt_pubkey = 3;
   */
  decryptPubkey: string;

  /**
   * Base64 std-encoded ECDSA P-256 ASN.1 DER signature.
   *
   * @generated from field: string sig = 4;
   */
  sig: string;

  /**
   * Unix timestamp in seconds. int32 keeps the JSON encoding a number.
   *
   * @generated from field: int32 timestamp = 5;
   */
  timestamp: number;
};

/**
 * Describes the message dicode.relay.v1.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export const HelloSchema: GenMessage<Hello> = /*@__PURE__*/ messageDesc(file_relay, 3);

/**
 * Welcome acknowledges a successful handshake and hands the daemon its
 * publicly reachable tunnel URL plus the broker's long-lived signing pubkey
 * for TOFU pinning.
 *
 * @generated from message dicode.relay.v1.Welcome
 */
export type Welcome = Message<"dicode.relay.v1.Welcome"> & {
  /**
   * Full WSS URL for this client, e.g. wss://relay.dicode.app/u/<uuid>/hooks/
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * Base64-encoded SPKI DER public key the broker uses to sign delivery
   * envelopes. Absent for brokers that don't support OAuth delivery.
   *
   * @generated from field: optional string broker_pubkey = 2;
   */
  brokerPubkey?: string | undefined;

  /**
   * Protocol version announced by the broker. v3 means "types generated from
   * proto". Daemons that require >= 3 for OAuth read this on welcome.
   *
   * @generated from field: optional int32 protocol = 3;
   */
  protocol?: number | undefined;
};

/**
 * Describes the message dicode.relay.v1.Welcome.
 * Use `create(WelcomeSchema)` to create a new message.
 */
export const WelcomeSchema: GenMessage<Welcome> = /*@__PURE__*/ messageDesc(file_relay, 4);

/**
 * Error is any server-side rejection mid-session (bad signature, stale
 * timestamp, registry conflict, etc.). After sending Error the server closes
 * the connection.
 *
 * @generated from message dicode.relay.v1.Error
 */
export type Error = Message<"dicode.relay.v1.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message dicode.relay.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/ messageDesc(file_relay, 5);

/**
 * Request is an inbound HTTP request forwarded to the daemon.
 *
 * @generated from message dicode.relay.v1.Request
 */
export type Request = Message<"dicode.relay.v1.Request"> & {
  /**
   * UUIDv4 used to correlate the response.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: map<string, dicode.relay.v1.HeaderValues> headers = 4;
   */
  headers: { [key: string]: HeaderValues };

  /**
   * Base64-encoded request body bytes.
   *
   * @generated from field: string body = 5;
   */
  body: string;
};

/**
 * Describes the message dicode.relay.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/ messageDesc(file_relay, 6);

/**
 * Response is the daemon's reply to a forwarded request.
 *
 * @generated from message dicode.relay.v1.Response
 */
export type Response = Message<"dicode.relay.v1.Response"> & {
  /**
   * Matches the `id` from the corresponding Request.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int32 status = 2;
   */
  status: number;

  /**
   * @generated from field: map<string, dicode.relay.v1.HeaderValues> headers = 3;
   */
  headers: { [key: string]: HeaderValues };

  /**
   * Base64-encoded response body bytes.
   *
   * @generated from field: string body = 4;
   */
  body: string;
};

/**
 * Describes the message dicode.relay.v1.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema: GenMessage<Response> = /*@__PURE__*/ messageDesc(file_relay, 7);

/**
 * HeaderValues wraps a list of strings so it can be the value type of a
 * proto3 map (which does not allow repeated values directly). Both
 * protojson and protobuf-es emit the inner `values` field on the wire.
 *
 * @generated from message dicode.relay.v1.HeaderValues
 */
export type HeaderValues = Message<"dicode.relay.v1.HeaderValues"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message dicode.relay.v1.HeaderValues.
 * Use `create(HeaderValuesSchema)` to create a new message.
 */
export const HeaderValuesSchema: GenMessage<HeaderValues> =
  /*@__PURE__*/
  messageDesc(file_relay, 8);

/**
 * OAuthTokenDelivery is the body of the `/hooks/oauth-complete` webhook the
 * broker forwards to the daemon after a successful OAuth exchange. It is
 * transported inside a Request.body (base64-encoded JSON); this message type
 * itself is not a ServerMessage variant.
 *
 * The ciphertext has the 16-byte AES-GCM authentication tag appended; the
 * daemon must split the last 16 bytes off before passing to aesGCM.Open.
 *
 * @generated from message dicode.relay.v1.OAuthTokenDelivery
 */
export type OAuthTokenDelivery = Message<"dicode.relay.v1.OAuthTokenDelivery"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Base64-encoded uncompressed P-256 ephemeral public key (65 bytes).
   *
   * @generated from field: string ephemeral_pubkey = 2;
   */
  ephemeralPubkey: string;

  /**
   * Base64-encoded ciphertext with auth tag appended.
   *
   * @generated from field: string ciphertext = 3;
   */
  ciphertext: string;

  /**
   * Base64-encoded 12-byte AES-GCM nonce (IV).
   *
   * @generated from field: string nonce = 4;
   */
  nonce: string;

  /**
   * Base64-encoded ECDSA P-256 signature over
   * sha256(session_id || ephemeral_pubkey || ciphertext || nonce). Signed by
   * the broker's long-lived key announced in Welcome.broker_pubkey.
   *
   * @generated from field: optional string broker_sig = 5;
   */
  brokerSig?: string | undefined;
};

/**
 * Describes the message dicode.relay.v1.OAuthTokenDelivery.
 * Use `create(OAuthTokenDeliverySchema)` to create a new message.
 */
export const OAuthTokenDeliverySchema: GenMessage<OAuthTokenDelivery> =
  /*@__PURE__*/
  messageDesc(file_relay, 9);
