// Protocol schema for the dicode relay WebSocket tunnel.
//
// Generated via protoc-gen-es → src/relay/pb/*.ts (`buf generate`).
//
// Wire format is JSON (WebSocket text frames) shaped by @bufbuild/protobuf's
// fromJson/toJson over the generated oneof envelopes.
//
// Protocol version: 4 (mTLS control channel). The daemon authenticates by
// presenting a self-signed TLS client certificate wrapping its P-256 signing
// key on the broker's dedicated mTLS listener; the broker derives
// uuid = hex(sha256(uncompressed_cert_pubkey)) from the peer certificate.
// There is no application-level challenge/signature exchange — channel
// binding comes from TLS 1.3 CertificateVerify.
//
// Both sides MUST reject connections where the peer advertises protocol < 4.

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=.js"
// @generated from file relay.proto (package dicode.relay.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file relay.proto.
 */
export const file_relay: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CgtyZWxheS5wcm90bxIPZGljb2RlLnJlbGF5LnYxIqsBCg1TZXJ2ZXJNZXNzYWdlEisKB3dlbGNvbWUYAiABKAsyGC5kaWNvZGUucmVsYXkudjEuV2VsY29tZUgAEicKBWVycm9yGAMgASgLMhYuZGljb2RlLnJlbGF5LnYxLkVycm9ySAASKwoHcmVxdWVzdBgEIAEoCzIYLmRpY29kZS5yZWxheS52MS5SZXF1ZXN0SABCBgoEa2luZEoECAEQAlIJY2hhbGxlbmdlIm8KDUNsaWVudE1lc3NhZ2USJwoFaGVsbG8YASABKAsyFi5kaWNvZGUucmVsYXkudjEuSGVsbG9IABItCghyZXNwb25zZRgCIAEoCzIZLmRpY29kZS5yZWxheS52MS5SZXNwb25zZUgAQgYKBGtpbmQiVQoFSGVsbG8SFgoOZGVjcnlwdF9wdWJrZXkYAyABKAlKBAgBEAJKBAgCEANKBAgEEAVKBAgFEAZSBHV1aWRSBnB1YmtleVIDc2lnUgl0aW1lc3RhbXAiaAoHV2VsY29tZRILCgN1cmwYASABKAkSGgoNYnJva2VyX3B1YmtleRgCIAEoCUgAiAEBEhUKCHByb3RvY29sGAMgASgFSAGIAQFCEAoOX2Jyb2tlcl9wdWJrZXlCCwoJX3Byb3RvY29sIhgKBUVycm9yEg8KB21lc3NhZ2UYASABKAkiyAEKB1JlcXVlc3QSCgoCaWQYASABKAkSDgoGbWV0aG9kGAIgASgJEgwKBHBhdGgYAyABKAkSNgoHaGVhZGVycxgEIAMoCzIlLmRpY29kZS5yZWxheS52MS5SZXF1ZXN0LkhlYWRlcnNFbnRyeRIMCgRib2R5GAUgASgJGk0KDEhlYWRlcnNFbnRyeRILCgNrZXkYASABKAkSLAoFdmFsdWUYAiABKAsyHS5kaWNvZGUucmVsYXkudjEuSGVhZGVyVmFsdWVzOgI4ASK8AQoIUmVzcG9uc2USCgoCaWQYASABKAkSDgoGc3RhdHVzGAIgASgFEjcKB2hlYWRlcnMYAyADKAsyJi5kaWNvZGUucmVsYXkudjEuUmVzcG9uc2UuSGVhZGVyc0VudHJ5EgwKBGJvZHkYBCABKAkaTQoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEoCRIsCgV2YWx1ZRgCIAEoCzIdLmRpY29kZS5yZWxheS52MS5IZWFkZXJWYWx1ZXM6AjgBIh4KDEhlYWRlclZhbHVlcxIOCgZ2YWx1ZXMYASADKAkijQEKEk9BdXRoVG9rZW5EZWxpdmVyeRISCgpzZXNzaW9uX2lkGAEgASgJEhgKEGVwaGVtZXJhbF9wdWJrZXkYAiABKAkSEgoKY2lwaGVydGV4dBgDIAEoCRINCgVub25jZRgEIAEoCRIXCgpicm9rZXJfc2lnGAUgASgJSACIAQFCDQoLX2Jyb2tlcl9zaWdCL1otZ2l0aHViLmNvbS9kaWNvZGUvZGljb2RlL3BrZy9yZWxheS9wYjtyZWxheXBiYgZwcm90bzM",
  );

/**
 * ServerMessage is any message the relay server sends to the daemon.
 * Wire form: a JSON object with one key identifying the variant, e.g.
 *   {"welcome": {"url": "..."}}.
 *
 * @generated from message dicode.relay.v1.ServerMessage
 */
export type ServerMessage = Message<"dicode.relay.v1.ServerMessage"> & {
  /**
   * @generated from oneof dicode.relay.v1.ServerMessage.kind
   */
  kind:
    | {
        /**
         * @generated from field: dicode.relay.v1.Welcome welcome = 2;
         */
        value: Welcome;
        case: "welcome";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Error error = 3;
         */
        value: Error;
        case: "error";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Request request = 4;
         */
        value: Request;
        case: "request";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message dicode.relay.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> =
  /*@__PURE__*/
  messageDesc(file_relay, 0);

/**
 * ClientMessage is any message the daemon sends to the relay server.
 *
 * @generated from message dicode.relay.v1.ClientMessage
 */
export type ClientMessage = Message<"dicode.relay.v1.ClientMessage"> & {
  /**
   * @generated from oneof dicode.relay.v1.ClientMessage.kind
   */
  kind:
    | {
        /**
         * @generated from field: dicode.relay.v1.Hello hello = 1;
         */
        value: Hello;
        case: "hello";
      }
    | {
        /**
         * @generated from field: dicode.relay.v1.Response response = 2;
         */
        value: Response;
        case: "response";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message dicode.relay.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> =
  /*@__PURE__*/
  messageDesc(file_relay, 1);

/**
 * Hello is the first frame the daemon sends after the TLS handshake.
 * The daemon's signing identity travels in its TLS client certificate;
 * hello only carries what TLS cannot: the ECIES recipient key.
 *
 * @generated from message dicode.relay.v1.Hello
 */
export type Hello = Message<"dicode.relay.v1.Hello"> & {
  /**
   * Base64 std-encoded 65-byte uncompressed P-256 public key (0x04 || X || Y).
   * Used as the ECIES recipient on OAuth token delivery.
   * Required — every daemon ships with a split sign/decrypt identity.
   *
   * @generated from field: string decrypt_pubkey = 3;
   */
  decryptPubkey: string;
};

/**
 * Describes the message dicode.relay.v1.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export const HelloSchema: GenMessage<Hello> = /*@__PURE__*/ messageDesc(file_relay, 2);

/**
 * Welcome acknowledges a successful handshake and hands the daemon its
 * publicly reachable tunnel URL plus the broker's delivery-signing pubkey.
 * The channel is TLS-server-authenticated, so the daemon can trust and
 * persist broker_pubkey on every connect (no TOFU pinning).
 *
 * @generated from message dicode.relay.v1.Welcome
 */
export type Welcome = Message<"dicode.relay.v1.Welcome"> & {
  /**
   * Full WSS URL for this client, e.g. wss://relay.dicode.app/u/<uuid>/hooks/
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * Base64-encoded SPKI DER public key the broker uses to sign delivery
   * envelopes. Absent for brokers that don't support OAuth delivery.
   *
   * @generated from field: optional string broker_pubkey = 2;
   */
  brokerPubkey?: string | undefined;

  /**
   * Protocol version announced by the broker. Daemons refuse < 4.
   *
   * @generated from field: optional int32 protocol = 3;
   */
  protocol?: number | undefined;
};

/**
 * Describes the message dicode.relay.v1.Welcome.
 * Use `create(WelcomeSchema)` to create a new message.
 */
export const WelcomeSchema: GenMessage<Welcome> = /*@__PURE__*/ messageDesc(file_relay, 3);

/**
 * Error is any server-side rejection mid-session (bad signature, stale
 * timestamp, registry conflict, etc.). After sending Error the server closes
 * the connection.
 *
 * @generated from message dicode.relay.v1.Error
 */
export type Error = Message<"dicode.relay.v1.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message dicode.relay.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/ messageDesc(file_relay, 4);

/**
 * Request is an inbound HTTP request forwarded to the daemon.
 *
 * @generated from message dicode.relay.v1.Request
 */
export type Request = Message<"dicode.relay.v1.Request"> & {
  /**
   * UUIDv4 used to correlate the response.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * @generated from field: string path = 3;
   */
  path: string;

  /**
   * @generated from field: map<string, dicode.relay.v1.HeaderValues> headers = 4;
   */
  headers: { [key: string]: HeaderValues };

  /**
   * Base64-encoded request body bytes.
   *
   * @generated from field: string body = 5;
   */
  body: string;
};

/**
 * Describes the message dicode.relay.v1.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/ messageDesc(file_relay, 5);

/**
 * Response is the daemon's reply to a forwarded request.
 *
 * @generated from message dicode.relay.v1.Response
 */
export type Response = Message<"dicode.relay.v1.Response"> & {
  /**
   * Matches the `id` from the corresponding Request.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int32 status = 2;
   */
  status: number;

  /**
   * @generated from field: map<string, dicode.relay.v1.HeaderValues> headers = 3;
   */
  headers: { [key: string]: HeaderValues };

  /**
   * Base64-encoded response body bytes.
   *
   * @generated from field: string body = 4;
   */
  body: string;
};

/**
 * Describes the message dicode.relay.v1.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema: GenMessage<Response> = /*@__PURE__*/ messageDesc(file_relay, 6);

/**
 * HeaderValues wraps a list of strings so it can be the value type of a
 * proto3 map (which does not allow repeated values directly). Both
 * protojson and protobuf-es emit the inner `values` field on the wire.
 *
 * @generated from message dicode.relay.v1.HeaderValues
 */
export type HeaderValues = Message<"dicode.relay.v1.HeaderValues"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message dicode.relay.v1.HeaderValues.
 * Use `create(HeaderValuesSchema)` to create a new message.
 */
export const HeaderValuesSchema: GenMessage<HeaderValues> =
  /*@__PURE__*/
  messageDesc(file_relay, 7);

/**
 * OAuthTokenDelivery is the body of the `/hooks/oauth-complete` webhook the
 * broker forwards to the daemon after a successful OAuth exchange. It is
 * transported inside a Request.body (base64-encoded JSON); this message type
 * itself is not a ServerMessage variant.
 *
 * The ciphertext has the 16-byte AES-GCM authentication tag appended; the
 * daemon must split the last 16 bytes off before passing to aesGCM.Open.
 *
 * @generated from message dicode.relay.v1.OAuthTokenDelivery
 */
export type OAuthTokenDelivery = Message<"dicode.relay.v1.OAuthTokenDelivery"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Base64-encoded uncompressed P-256 ephemeral public key (65 bytes).
   *
   * @generated from field: string ephemeral_pubkey = 2;
   */
  ephemeralPubkey: string;

  /**
   * Base64-encoded ciphertext with auth tag appended.
   *
   * @generated from field: string ciphertext = 3;
   */
  ciphertext: string;

  /**
   * Base64-encoded 12-byte AES-GCM nonce (IV).
   *
   * @generated from field: string nonce = 4;
   */
  nonce: string;

  /**
   * Base64-encoded ECDSA P-256 signature over the v4 delivery preimage
   * (see shared/signing.ts buildDeliverySignaturePayload: domain label +
   * length-prefixed fields). Signed by the broker's long-lived key announced
   * in Welcome.broker_pubkey.
   *
   * @generated from field: optional string broker_sig = 5;
   */
  brokerSig?: string | undefined;
};

/**
 * Describes the message dicode.relay.v1.OAuthTokenDelivery.
 * Use `create(OAuthTokenDeliverySchema)` to create a new message.
 */
export const OAuthTokenDeliverySchema: GenMessage<OAuthTokenDelivery> =
  /*@__PURE__*/
  messageDesc(file_relay, 8);
